
USE Restaurante;
-- Inserciones en la tabla Client (30 registros)
INSERT INTO Client (name) VALUES ('Juan Pérez');
INSERT INTO Client (name) VALUES ('María García');
INSERT INTO Client (name) VALUES ('Carlos Rodríguez');
INSERT INTO Client (name) VALUES ('Ana Martínez');
INSERT INTO Client (name) VALUES ('Luis Sánchez');
INSERT INTO Client (name) VALUES ('Marta Gómez');
INSERT INTO Client (name) VALUES ('José Díaz');
INSERT INTO Client (name) VALUES ('Laura Fernández');
INSERT INTO Client (name) VALUES ('Miguel Herrera');
INSERT INTO Client (name) VALUES ('Sara Romero');
INSERT INTO Client (name) VALUES ('Pedro López');
INSERT INTO Client (name) VALUES ('Elena Morales');
INSERT INTO Client (name) VALUES ('Andrés Rojas');
INSERT INTO Client (name) VALUES ('Sofía Ruiz');
INSERT INTO Client (name) VALUES ('Diego Vargas');
INSERT INTO Client (name) VALUES ('Claudia Castro');
INSERT INTO Client (name) VALUES ('Raúl Mendoza');
INSERT INTO Client (name) VALUES ('Carolina Navarro');
INSERT INTO Client (name) VALUES ('Jorge Torres');
INSERT INTO Client (name) VALUES ('Paula Aguirre');
INSERT INTO Client (name) VALUES ('Federico Silva');
INSERT INTO Client (name) VALUES ('Lorena Paredes');
INSERT INTO Client (name) VALUES ('Victor Campos');
INSERT INTO Client (name) VALUES ('Isabel Peña');
INSERT INTO Client (name) VALUES ('Esteban Fuentes');
INSERT INTO Client (name) VALUES ('Natalia Gil');
INSERT INTO Client (name) VALUES ('Rubén Lozano');
INSERT INTO Client (name) VALUES ('Verónica Ibáñez');
INSERT INTO Client (name) VALUES ('Guillermo Ortega');
INSERT INTO Client (name) VALUES ('Alma Cabrera');

-- Inserciones en la tabla Product (30 registros)
INSERT INTO Product (name, prize, stock) VALUES ('Pizza Margarita', 8.50, 50);
INSERT INTO Product (name, prize, stock) VALUES ('Pizza Pepperoni', 9.50, 50);
INSERT INTO Product (name, prize, stock) VALUES ('Ensalada César', 6.75, 40);
INSERT INTO Product (name, prize, stock) VALUES ('Lasaña Boloñesa', 10.00, 30);
INSERT INTO Product (name, prize, stock) VALUES ('Sopa de Pollo', 5.50, 20);
INSERT INTO Product (name, prize, stock) VALUES ('Hamburguesa Clásica', 7.50, 60);
INSERT INTO Product (name, prize, stock) VALUES ('Filete de Res', 15.00, 25);
INSERT INTO Product (name, prize, stock) VALUES ('Pasta Alfredo', 12.50, 35);
INSERT INTO Product (name, prize, stock) VALUES ('Sushi Variado', 14.00, 40);
INSERT INTO Product (name, prize, stock) VALUES ('Tacos al Pastor', 8.00, 45);
INSERT INTO Product (name, prize, stock) VALUES ('Burritos de Pollo', 9.00, 30);
INSERT INTO Product (name, prize, stock) VALUES ('Paella Mixta', 18.00, 20);
INSERT INTO Product (name, prize, stock) VALUES ('Risotto de Hongos', 13.50, 25);
INSERT INTO Product (name, prize, stock) VALUES ('Steak a la Parrilla', 20.00, 20);
INSERT INTO Product (name, prize, stock) VALUES ('Pollo al Curry', 11.00, 40);
INSERT INTO Product (name, prize, stock) VALUES ('Ceviche de Pescado', 12.00, 15);
INSERT INTO Product (name, prize, stock) VALUES ('Bocadillo de Jamón', 6.50, 30);
INSERT INTO Product (name, prize, stock) VALUES ('Crepas de Nutella', 4.50, 50);
INSERT INTO Product (name, prize, stock) VALUES ('Arepas Rellenas', 5.75, 35);
INSERT INTO Product (name, prize, stock) VALUES ('Empanadas de Carne', 3.50, 40);
INSERT INTO Product (name, prize, stock) VALUES ('Quiche Lorraine', 7.00, 25);
INSERT INTO Product (name, prize, stock) VALUES ('Tabulé', 6.25, 30);
INSERT INTO Product (name, prize, stock) VALUES ('Gazpacho Andaluz', 5.00, 35);
INSERT INTO Product (name, prize, stock) VALUES ('Calamares Fritos', 9.50, 25);
INSERT INTO Product (name, prize, stock) VALUES ('Brownie de Chocolate', 4.75, 40);
INSERT INTO Product (name, prize, stock) VALUES ('Helado de Vainilla', 3.75, 50);
INSERT INTO Product (name, prize, stock) VALUES ('Café Espresso', 2.50, 60);
INSERT INTO Product (name, prize, stock) VALUES ('Té Helado', 3.00, 55);
INSERT INTO Product (name, prize, stock) VALUES ('Smoothie de Fresa', 5.25, 45);
INSERT INTO Product (name, prize, stock) VALUES ('Limonada', 2.00, 50);

-- Inserciones en la tabla Orders (30 registros)
-- Se asigna el número de mesa de 1 a 10 de forma cíclica y se enlaza con el idClient correspondiente (1 a 30)
INSERT INTO Orders (`table`, idClient) VALUES (1, 1);
INSERT INTO Orders (`table`, idClient) VALUES (2, 2);
INSERT INTO Orders (`table`, idClient) VALUES (3, 3);
INSERT INTO Orders (`table`, idClient) VALUES (4, 4);
INSERT INTO Orders (`table`, idClient) VALUES (5, 5);
INSERT INTO Orders (`table`, idClient) VALUES (6, 6);
INSERT INTO Orders (`table`, idClient) VALUES (7, 7);
INSERT INTO Orders (`table`, idClient) VALUES (8, 8);
INSERT INTO Orders (`table`, idClient) VALUES (9, 9);
INSERT INTO Orders (`table`, idClient) VALUES (10, 1);
INSERT INTO Orders (`table`, idClient) VALUES (1, 11);
INSERT INTO Orders (`table`, idClient) VALUES (2, 12);
INSERT INTO Orders (`table`, idClient) VALUES (3, 13);
INSERT INTO Orders (`table`, idClient) VALUES (4, 1);
INSERT INTO Orders (`table`, idClient) VALUES (5, 15);
INSERT INTO Orders (`table`, idClient) VALUES (6, 16);
INSERT INTO Orders (`table`, idClient) VALUES (7, 17);
INSERT INTO Orders (`table`, idClient) VALUES (8, 18);
INSERT INTO Orders (`table`, idClient) VALUES (9, 19);
INSERT INTO Orders (`table`, idClient) VALUES (10, 20);
INSERT INTO Orders (`table`, idClient) VALUES (1, 21);
INSERT INTO Orders (`table`, idClient) VALUES (2, 22);
INSERT INTO Orders (`table`, idClient) VALUES (3, 23);
INSERT INTO Orders (`table`, idClient) VALUES (4, 24);
INSERT INTO Orders (`table`, idClient) VALUES (5, 25);
INSERT INTO Orders (`table`, idClient) VALUES (6, 26);
INSERT INTO Orders (`table`, idClient) VALUES (7, 27);
INSERT INTO Orders (`table`, idClient) VALUES (8, 28);
INSERT INTO Orders (`table`, idClient) VALUES (9, 29);
INSERT INTO Orders (`table`, idClient) VALUES (10, 30);

-- Inserciones en la tabla OrderDetails (30 registros)
-- Se relaciona cada orden con un producto usando el mismo número (para simplificar el ejemplo)
-- Se asume que el precio del detalle es el precio en el momento de la orden y se define una cantidad arbitraria
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (1, 1, 2, 8.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (2, 2, 1, 9.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (3, 3, 3, 6.75);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (4, 4, 2, 10.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (5, 5, 1, 5.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (6, 6, 2, 7.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (7, 7, 1, 15.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (8, 8, 2, 12.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (9, 9, 1, 14.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (10, 10, 3, 8.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (11, 11, 2, 9.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (12, 12, 1, 18.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (13, 13, 2, 13.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (14, 14, 1, 20.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (15, 15, 2, 11.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (16, 16, 3, 12.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (17, 17, 1, 6.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (18, 18, 2, 4.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (19, 19, 1, 5.75);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (20, 20, 3, 3.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (21, 21, 2, 7.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (22, 22, 1, 6.25);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (23, 23, 2, 5.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (24, 24, 1, 9.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (25, 25, 2, 4.75);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (26, 26, 3, 3.75);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (27, 27, 1, 2.50);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (28, 28, 2, 3.00);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (29, 29, 1, 5.25);
INSERT INTO OrderDetails (ProductId, OrderId, quantity, prize) VALUES (30, 30, 2, 2.00);
